# Docker Compose file for a Baikal server with local mounts instead of Docker volumes

# Before you start docker-compose up, make sure that you have prepared
# the local folders to avoid file permission issues with
#
# mkdir -p config Specific/db
# chown -R 101:101 config Specific

services:
  baikal:
    image: ghcr.io/mralucarddante/baikal-docker-hass:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config:/var/www/baikal/config
      - ./Specific:/var/www/baikal/Specific
