# Docker Compose file for a Baikal server

version: "2"
services:
  baikal:
    image: ghcr.io/mralucarddante/baikal-docker-hass:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific

volumes:
  config:
  data:
