# Docker Compose file for a Baikal server
# See https://github.com/MrAlucardDante/baikal-docker-hass/blob/master/docs/email-guide.md

services:
  baikal:
    image: ghcr.io/mralucarddante/baikal-docker-hass:latest
    restart: always
    environment:
      MSMTPRC: |
        defaults
        auth           on
        tls            on
        tls_trust_file /etc/ssl/certs/ca-certificates.crt
        account        default
        host           smtp.gmail.com
        port           587
        from           <user>@gmail.com
        user           <user>
        password       <password>
    ports:
      - "80:80"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific

volumes:
  config:
  data:
